### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by ew1abz**
+ Update the gettext version to fix warnings.

### CODE REVIEW

**Comment by ew1abz** [comment]
Sorry @fillods, my last PR broke the build. Your fix, unfortunately, didn't help. I tested the build process using Github actions: https://github.com/ew1abz/grig/blob/github-actions/.github/workflows/makefile.yml
I'll clean up the branch and open a new PR after you merge this one.

**Comment by ew1abz** [comment]
Hi @fillods. I just want to make sure you saw the PR. The build process is broken right now, even with your latest commit.

**Comment by fillods** [comment]
Thanks @ew1abz, I did saw your PR but wanted to take time to do some more cleanup. The PR was not merged but parts were integrated in the master branch. Let me know how it works for you.
I hope to put in place the automatic build process based on yours soon.

**Comment by ew1abz** [comment]
Awesome cleanup, @fillods! Your changes work for me. It's still a lot of warnings about deprecated Autoconf and Gtk stuff. Unfortunately, I don't know Autotools at all, but fixing Gtk warnings look like a logical next step for me. BTW, GitHub action PR is open. Please feel free to modify it.

**Pull request closed without merging**
